### ISSUE TITLE
Unexpected behavior caused by obsolete imports in tests

### ISSUE THREAD

**Issue by trp-samer-adra** [ahmetalpbalkan/go-dexec#11]
I have a project that depends on this dependency and uses go modules and runs `go mod tidy`.
About five months ago the pipeline started failing despite no change no my end.
What was happening was a test that was timing out when running a Docker command using this package.
I noticed that `go mod tidy` kept adding an indirect dependency to "github.com/ahmetalpbalkan/go-dexec" and when that dependency was in my go.mod (along with the direct dependency on this lib in its current location under ahmetb), the test would timeout. When the "github.com/ahmetalpbalkan/go-dexec" indirect dependency was not in go.mod, the test succeeded.

`go mod why github.com/ahmetalpbalkan/go-dexec` revealed the indirect dependency was getting pulled in because the old package is still being referenced by several tests (and go mod tidy isn't smart enough to exclude that).

Simply need to change ahmetalpbalkan to ahmetb as the old repo and its packages no longer exist.

**Comment by ahmetb** [comment]
Feel free to send a PR.

**Comment by trp-samer-adra** [comment]
> Feel free to send a PR.

Thanks, here you go:
https://github.com/ahmetb/go-dexec/pull/12
