### ISSUE TITLE
docker volume parameter

### ISSUE THREAD

**Issue by prvst** [ahmetalpbalkan/go-dexec#2]
Hi, nice project.
Is it possible to share a volume and files using your library (ex: docker run -v /home/user/:/home/ container <program>) ?

**Comment by ahmetb** [comment]
@prvst yes. Anything docker API supports is also supported here. You can explore https://godoc.org/github.com/fsouza/go-dockerclient to see how you can pass the volume options.

**Comment by prvst** [comment]
cool, thanks
